"""Import test parameters"""

from tests.parameters.element_lists import PARAMETERS_ELEMENT_LISTS
from tests.parameters.elements import (
    PARAMETERS_ELEMENTS,
    PARAMETERS_ELEMENTS_BOOLEAN,
    PARAMETERS_ELEMENTS_DOUBLE,
    PARAMETERS_ELEMENTS_INTEGER,
    PARAMETERS_ELEMENTS_IRI,
    PARAMETERS_ELEMENTS_LITERAL_BOOLEAN,
    PARAMETERS_ELEMENTS_LITERAL_DOUBLE,
    PARAMETERS_ELEMENTS_LITERAL_INTEGER,
    PARAMETERS_ELEMENTS_LITERAL_LANGSTRING,
    PARAMETERS_ELEMENTS_LITERAL_STRING,
    PARAMETERS_ELEMENTS_STRING,
)
from tests.parameters.identifiers import PARAMETERS_IDENTIFIERS
from tests.parameters.key_functions import PARAMETERS_KEY_FUNCTIONS
from tests.parameters.labels import PARAMETERS_LABELS
from tests.parameters.langs import PARAMETERS_LANGS
from tests.parameters.models import (
    PARAMETERS_ALT,
    PARAMETERS_BAG,
    PARAMETERS_BLANK_NODE_OBJECTS,
    PARAMETERS_CLASS,
    PARAMETERS_COLLECTIONS,
    PARAMETERS_FUNCTIONAL_PROPERTY,
    PARAMETERS_INVERSE_FUNCTIONAL_PROPERTY,
    PARAMETERS_LABELED_OBJECTS,
    PARAMETERS_LIST,
    PARAMETERS_ONTOLOGY,
    PARAMETERS_PROPERTY,
    PARAMETERS_RESOURCE,
    PARAMETERS_SEQ,
    PARAMETERS_SYMMETRIC_PROPERTY,
    PARAMETERS_TRANSITIVE_PROPERTY,
)
from tests.parameters.namespaces import PARAMETERS_NAMESPACES
from tests.parameters.paths import PARAMETERS_PATHS
from tests.parameters.properties import (
    PARAMETERS_PROPERTIES_CLASS,
    PARAMETERS_PROPERTIES_CONTAINER,
    PARAMETERS_PROPERTIES_LIST,
    PARAMETERS_PROPERTIES_OBJECTS_RESOURCE,
    PARAMETERS_PROPERTIES_ONTOLOGY,
    PARAMETERS_PROPERTIES_PROPERTY,
    PARAMETERS_PROPERTIES_RESOURCE,
    PARAMETERS_PROPERTIES_TO_OBJECTS_RESOURCE,
)
from tests.parameters.versions import PARAMETERS_VERSIONS

__all__ = [
    "PARAMETERS_ELEMENT_LISTS",
    "PARAMETERS_ELEMENTS",
    "PARAMETERS_ELEMENTS_BOOLEAN",
    "PARAMETERS_ELEMENTS_DOUBLE",
    "PARAMETERS_ELEMENTS_INTEGER",
    "PARAMETERS_ELEMENTS_IRI",
    "PARAMETERS_ELEMENTS_LITERAL_BOOLEAN",
    "PARAMETERS_ELEMENTS_LITERAL_DOUBLE",
    "PARAMETERS_ELEMENTS_LITERAL_INTEGER",
    "PARAMETERS_ELEMENTS_LITERAL_LANGSTRING",
    "PARAMETERS_ELEMENTS_LITERAL_STRING",
    "PARAMETERS_ELEMENTS_STRING",
    "PARAMETERS_IDENTIFIERS",
    "PARAMETERS_KEY_FUNCTIONS",
    "PARAMETERS_LABELS",
    "PARAMETERS_LANGS",
    "PARAMETERS_ALT",
    "PARAMETERS_BAG",
    "PARAMETERS_BLANK_NODE_OBJECTS",
    "PARAMETERS_CLASS",
    "PARAMETERS_FUNCTIONAL_PROPERTY",
    "PARAMETERS_INVERSE_FUNCTIONAL_PROPERTY",
    "PARAMETERS_LABELED_OBJECTS",
    "PARAMETERS_LIST",
    "PARAMETERS_ONTOLOGY",
    "PARAMETERS_COLLECTIONS",
    "PARAMETERS_PROPERTY",
    "PARAMETERS_RESOURCE",
    "PARAMETERS_SEQ",
    "PARAMETERS_SYMMETRIC_PROPERTY",
    "PARAMETERS_TRANSITIVE_PROPERTY",
    "PARAMETERS_NAMESPACES",
    "PARAMETERS_PATHS",
    "PARAMETERS_PROPERTIES_CLASS",
    "PARAMETERS_PROPERTIES_CONTAINER",
    "PARAMETERS_PROPERTIES_LIST",
    "PARAMETERS_PROPERTIES_ONTOLOGY",
    "PARAMETERS_PROPERTIES_PROPERTY",
    "PARAMETERS_PROPERTIES_RESOURCE",
    "PARAMETERS_PROPERTIES_OBJECTS_RESOURCE",
    "PARAMETERS_PROPERTIES_TO_OBJECTS_RESOURCE",
    "PARAMETERS_VERSIONS",
]
